#ifndef KERNEL_BUSMASTERDRIVERINTERFACE_IBUSSERVICE_H_
#define KERNEL_BUSMASTERDRIVERINTERFACE_IBUSSERVICE_H_

class IBusService {
 public:
};

#endif  // KERNEL_BUSMASTERDRIVERINTERFACE_IBUSSERVICE_H_